[[pages]]
path = "Home.py"
name = "ğŸ  é¦–é¡µ"
icon = ""

[[pages]]
path = "pages/50percentthreshold.py"
name = "ğŸ”¹ 50% ç¼©è¶³é˜ˆå€¼è®¡ç®—å·¥å…·ï¼ˆç»å…¸up-downæ³•ï¼‰"
icon = ""

[[pages]]
path = "pages/sudolookup_tool.py"
name = "ğŸ”¹ SUDO å·¥å…·ï¼ˆç®€åŒ–ç‰ˆ von Freyï¼‰"
icon = ""
