[[pages]]
path = "Home.py"
name = "ğŸ  é¦–é¡µ"

[[pages]]
path = "pages/50_percent_threshold.py"
name = "ğŸ”¹ 50% ç¼©è¶³é˜ˆå€¼è®¡ç®—å·¥å…·ï¼ˆç»å…¸up-downæ³•ï¼‰"

[[pages]]
path = "pages/sudo_lookup_tool.py"
name = "ğŸ”¹ SUDO å·¥å…·ï¼ˆç®€åŒ–ç‰ˆ von Freyï¼‰"
